version: '3.4'

services:
  builder.clean-arch:
    container_name: builder.clean-arch
    build: .
    volumes:
      - .:/app
    ports:
      - "5001:5001"

  mysql.clean-arch:
    container_name: mysql.clean-arch
    image: mysql:5.7
    volumes:
      - clean-arch-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=clean-arch
      - MYSQL_ROOT_PASSWORD=root

volumes:
  clean-arch-mysql:

networks:
  bubble:
    external: true
