version: '3.4'

services:
  app.clean-architecture:
    container_name: app.clean-architecture
    build: .
    volumes:
      - .:/app
    ports:
      - "5001:5001"

  mysql.clean-architecture:
    container_name: mysql.clean-architecture
    image: mysql:5.7
    volumes:
      - clean-architecture-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=clean-architecture
      - MYSQL_ROOT_PASSWORD=root

volumes:
  clean-architecture-mysql:

networks:
  bubble:
    external: true
