version: '3.4'

services:
  builder.clean-arch:
    container_name: builder.clean-arch
    build: .
    volumes:
      - .:/app
    ports:
      - "5001:5001"

  mysql.clean-arch:
    container_name: mysql.clean-arch
    image: mysql:5.7
    volumes:
      - clean-arch-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=clean-architecture
      - MYSQL_ROOT_PASSWORD=root

  mongo:
    container_name: mongo.clean-arch
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017

volumes:
  clean-arch-mysql:
    external: false
  mongodb_data:
    external: false

networks:
  bubble:
    external: true
